name: Rerun HTML scraping on Metrograph website

on:
  workflow_dispatch: # allow manual runs

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install Python dependencies
        run: |
          pip install -r scripts/scrap/requirements.txt

      - name: Pull raw html
        run: |
          python -u scripts/scrap/getRawHtml.py

      - name: Commit raw html files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/scrap/data/raw_films.json
          git add scripts/scrap/data/raw_events.json
          git add scripts/scrap/data/metrograph.html
          git add scripts/scrap/data/metrograph_events.html
          git commit -m "Update raw html files [skip ci]" || echo "No changes to commit"
          git push
