name: Grab Metrograph films for the week

on:
  schedule:
    - cron: '0 14 * * 1' # Every Monday at 10:00 AM ET
  workflow_dispatch: # allow manual runs

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          pip install -r scripts/scrap/requirements.txt
          pip install webdriver-manager

      - name: Run script
        run: |
          python scripts/scrap/getShowtimes.py

      - name: Commit data files
        run: |
          git add scripts/scrap/data/raw_films.json
          git add scripts/scrap/data/parsed_films.csv
          git add scripts/scrap/data/skipped_films.csv
          git commit -m "Update files [skip ci]" || echo "No changes to commit"
          git push
