name: Grab Metrograph films for the week

on:
  schedule:
    # Every Monday at 10:00 AM Eastern Time
    - cron: '0 14 * * 1' # 14:00 UTC = 10:00 ET
  workflow_dispatch: # allow manual runs too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          pip install -r ./scrap/requirements.txt
          pip install webdriver-manager

      - name: Run script
        run: |
          python ./scrap/getShowtimes.py
